paritytech/testnet-manager

app/lib/cron_tasks.py

The `network` argument was removed from  `list_validator_stateful_sets`.

Fix cron task

---

main.py
task-scheduler.py

If application deployed with kubernetes readiness probe, the log output will be spammed by `"GET /health HTTP/1.1"` string. Which is not very useful and only complicates the debugging.

Disable health check logs

---

app/lib/substrate.py

Closes: #5 
Any exception on `SubstrateInterface(url=url).websocket.ping()` should be properly handled. 
- Replace list of exception  with general exception.

Fix ws pool exception list

---

app/lib/collator_manager.py
app/lib/collator_mint.py
app/lib/network_utils.py
app/routers/apis.py

We have if case:
```
if not any(d['who'].lower() == keypair.ss58_address.lower() for d in candidates)
```
Which used to determent do we need to execute  register/deregister task. `candidates` map contains key in one `ss58_format ` and   `keypair.ss58_address` can use  another.

make ss58_format mandatory option for collator register/deregister

---

app/lib/balance_utils.py
app/lib/collator_mint.py
app/lib/collator_moonbeam.py
app/lib/stash_accounts.py
tests/balance_utils_test.py

Fixes: https://github.com/paritytech/testnet-manager/issues/17
`fund_accounts` function was very slow it takes at least 6 sec to fund one account.  The new function uses `bacth_all` call and can fund all accounts in one call. I also replaced the `wait` loop with `wait_for_inclusion=true` parameter of the substrate call (`true` is the default value).
Speed improvements for 20 accounts:
before:
`~2min`
now:
`less than 6 sec`

Rewrite transfer_funds function

---

app/lib/network_utils.py

The logic issue is illustrated with this example.
We had:
```
>>> list(set([1,2,3]).intersection(set([1,2])))
[1, 2]
```
Whereas we want:
```
>>> list(set([1,2,3]).difference(set([1,2])))
[3]
```

Fix logic to remove invulnerable collators

---

app/lib/network_utils.py
app/lib/stash_accounts.py
local-kubernetes/Makefile

1. Runtime is not available in most parachains page, this is likely due to the use of `try-catch` statements.   I moved `get_last_runtime_upgrade` out from `try-catch`. This is safe since  `get_last_runtime_upgrade` already have `try-catch` statements inside function.  
2. If account not created the node page will fail:  
```
File "/app/app/lib/stash_accounts.py", line 26, in get_account_funds
return substrate_query_url(ws_endpoint, 'System', 'Account', [account_address])['data']['free']
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
TypeError: tuple indices must be integers or slices, not str
```
3. fix Makefile

Small fixes for node_info page 

---

app/lib/network_utils.py
app/routers/views.py
app/templates/validators.html

In a testnet for which multiple organizations are running validators eg. Westend. It's important not to have the current "deregister deleted validator button" which would have the effect to deregister all unknown validators. This button functionality can now be easily performed with the API so it's no longer needed.

Validator view improvements for listing unknown validators

---

app/lib/balance_utils.py
app/lib/collator_mint.py
app/lib/parachain_manager.py
app/lib/stash_accounts.py
app/lib/substrate.py
app/routers/apis.py
tests/balance_utils_test.py
tests/stash_account_test.py

Also automatically adds the right number of decimals per UNIT.
Remark: docker tests are broken but the issue is also affecting the main branch.

Add balance transfer API

---

app/lib/balance_utils.py
app/lib/collator_manager.py
app/lib/collator_mint.py
app/lib/parachain_manager.py
app/lib/runtime_utils.py
app/lib/substrate.py
local-kubernetes/charts/helmfile-rococo.yaml
local-kubernetes/charts/helmfile-wococo.yaml

fix: https://github.com/paritytech/testnet-manager/issues/72
1. add function to calculate weight and fee
2. Fix local-kubernetis helm charts 
3. Fix mint base collator

Use transactionPaymentCallApi.queryCallInfo to set weights dynamically on XCM calls

---

app/lib/parachain_manager.py
app/lib/substrate.py

New parachain runtime has `checkVersion: bool` field:
Old runtime: 
1. add support for `checkVersion`
2. fix `get_query_info` function (`shell` runtime fails on `create_signed_extrinsic` step. )

Add support of `checkVersion` in parachain_runtime_upgrade function

---

.github/workflows/smoke_test.yml
app/routers/views.py
local-kubernetes/Makefile
tests/smoke_test.sh

Added smoke test to ensure that all testnet-manager links are working.
1. CI starts minikube  and deploy example setup from `local-kubernetes` folder.
2. Run `smoke_test.sh` script which opens links  in testnet-manager 
3. if page is not working the CI will fail, for example [jobs#8921387934](https://github.com/paritytech/testnet-manager/actions/runs/4983838146/jobs/8921387934)
4. If CI is successful the html files will be uploaded as artifacts (for example [artifacts](https://github.com/paritytech/testnet-manager/actions/runs/4983946977)).  
HTML files in artifacts should be available for preview, but for security reasons, it is not possible to open html page on github.com (html page may contain a script that will be executed).  We need to upload them to separate places and post links in …

Add smoke test

---

app/lib/collator_account.py
app/lib/collator_mint.py
app/routers/apis.py

Different parachains uses different key types, for example: 
```
statemine - sr25519
statemint - Ed25519
```
1. Use runtime call to generate aura key.
2. Fix api call `set_on_chain_keys`

generate aura key with api call

---

app/lib/runtime_utils.py
app/routers/apis.py
tests/node_utils_test.py
tests/smoke_test.sh

Add API to retrieve runtime metadatas as file

---

app/config/network_configuration.py

Rotate key operations was erroneously attempted on `ws://versi-validator-a-node-11.versi:9944` but it is using HTTP and not WS.

Fix http protocol prefix returned in node_http_endpoint

---

app/lib/kubernetes_client.py
app/routers/views.py
app/templates/node_info.html
local-kubernetes/charts/helmfile-rococo.yaml

Closes https://github.com/paritytech/testnet-manager/issues/87
Sample of new node page:

Add kubernetes metadata for each node

---

local-kubernetes/Makefile
local-kubernetes/README.md
local-kubernetes/charts/values-moonbase-collator.yml
local-kubernetes/charts/values-testnet-manager.yml
skaffold.yaml
tests/stash_account_test.py

- naming corrections
- fix moonbase failure by removing legacy flags
- add proper support for podman
- improve cleanup

Testnet manager local setup improvements

---

app/lib/collator_manager.py
app/lib/network_utils.py
app/routers/apis.py
local-kubernetes/Makefile
local-kubernetes/charts/helmfile-rococo.yaml

Resolves: https://github.com/paritytech/testnet-manager/issues/88
* Added two new endpoint to add and remove invulnerables via {add, remove}_invulnerable pallet
* Retain the set_invulnerable endpoint to behave as set_invulnerable pallet

[Feature] Add/Remove invlunerables

---

app/lib/collator_account.py
tests/docker-compose.yml

fix for: https://github.com/paritytech/testnet-manager/issues/114
1. if rpc `generate_session_keys` is not available return the most common key `SR25519`
2. fix test

fix get_derived_collator_session_keys

---

app/lib/substrate.py
scripts/get-extrinsic-call.py
tests/substrate_test.py

Fixes: https://github.com/paritytech/testnet-manager/issues/123

Sudo proxy support

---

app/lib/parachain_manager.py

We need to use `system.applyAuthorizedUpgrade` instead of `parachainSystem.enactAuthorizedUpgrade`

finalize switch to system authorize/apply upgrade
